$(document).ready(function(){
$(function(){
    $('.navbar-toggle').click(function(){
        $('.navbar-toggle').toggleClass('navbar-on');
        $('nav').fadeToggle();
        $('nav').removeClass('nav-hide');
    });
});
});